version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Logging in to AWS CodeArtifact..."
      # Pulls values dynamically from the variables you set up in the AWS Console
      - aws codeartifact login --tool mvn --repository project-devops-cicd --domain project --domain-owner 131707624275
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Maven project..."
      - mvn clean package
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no

